"""add is_active to categories and products

Revision ID: 5f9232e52779
Revises: e055ac11c428
Create Date: 2026-04-22 23:31:44.757941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9232e52779'
down_revision: Union[str, Sequence[str], None] = 'e055ac11c428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=1)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
