"""Add soft delete fields and update unique constraints with batch mode

Revision ID: 616d186c47c2
Revises: 6eb5bef51005
Create Date: 2026-04-22 21:58:04.159870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616d186c47c2'
down_revision: Union[str, Sequence[str], None] = '6eb5bef51005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_company_sku', ['company_id', 'sku'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uix_company_sku', type_='unique')

    # ### end Alembic commands ###
